# Generated by Django 3.0.7 on 2020-06-09 09:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='book_auths', to='books.Author'),
        ),
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.ManyToManyField(help_text='Selct a genre for this book', to='books.Genre'),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.Language'),
        ),
    ]
